courses/urls.py
from django.urls import path
from . import views

app_name ='courses'

urlpatterns = [
    path('',views.courseHome,name='all_courses'),
]

landing/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

app_name='landing'

urlpatterns = [
     path('',views.home,name="home"),
     path('terms/',views.terms,name="terms"),
     path('login/',views.loginUser,name="login"),
     path('signup/',views.signupUser,name="signup"),
     path('about/',views.about,name="about"),
     path('logout/',views.logoutUser,name="logout"),
     path('profile/',views.studentProfile,name="profile"),

     path('password_reset/',
          auth_views.PasswordResetView.as_view(template_name='landing/password_reset.html',success_url=reverse_lazy('landing:password_reset_done')),
               name="password_reset"),

     path('password_reset_sent/',
          auth_views.PasswordResetDoneView.as_view(template_name='landing/password_reset_sent.html'),
          name="password_reset_done"),

     path('reset/<uidb64>/<token>/',
          auth_views.PasswordResetConfirmView.as_view(template_name='landing/password_reset_form.html',success_url=reverse_lazy('landing:password_reset_complete')),
          name="password_reset_confirm"),

     path('password_reset_complete/',
          auth_views.PasswordResetCompleteView.as_view(template_name='landing/password_reset_done.html'),
          name="password_reset_complete"),

]

solarstudy/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('landing.urls')),
    path('courses/', include('courses.urls')),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

landing/models.py
from django.db import models
from django.contrib.auth.models import User


class StudentProfile(models.Model):
    user=models.OneToOneField(User,blank=True,on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

landing/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class UserSignupForm(UserCreationForm):
    class Meta:
        model = User
        fields=['first_name','last_name','username',
                    'email','password1','password2']
                    

courses/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required


@login_required(login_url="landing:login")
def courseHome(request):
    return render(request,'courses/all_courses.html')

landing/views.py
from django.shortcuts import render , redirect
from django.contrib.auth.forms import UserCreationForm
from .forms import UserSignupForm
from django.contrib import messages
from django.contrib.auth import login,logout,authenticate
from django.contrib.auth.decorators import login_required
from .decorators import unauthenticated_user

def home(request):
    return render(request,'landing/body.html')

def terms(request):
    return render(request,'landing/terms.html')

def about(request):
    return render(request,'landing/about.html')

@unauthenticated_user
def loginUser(request):
    if request.method =="POST":
        username=request.POST.get("username")
        password=request.POST.get("password")
        user=authenticate(request,username=username,password=password)
        if user is not None:
            login(request,user)
            return redirect('courses:all_courses')
        else:
            messages.info(request,"Username os Password is incorrect")

    return render(request,'landing/login.html')


def logoutUser(request):
    logout(request)
    return redirect('landing:home')

@unauthenticated_user
def signupUser(request):
    form=UserCreationForm()
    if request.method == 'POST':
        form=UserSignupForm(request.POST)
        if form.is_valid():
            form.save()
            user=form.cleaned_data.get("username")
            messages.success(request,user+", Your Account has been successfully created! Login To continue ")
            return redirect('landing:login')

    context={'form':form}
    return render(request,'landing/signup.html',context)

@login_required(login_url="landing:login")
def studentProfile(request):
    return render(request,'landing/profile.html')

courses/templates/courses/all_courses.html
{% extends 'landing/base.html' %} 
{% block content%}

<h1 style="text-align: center; padding: 20px;">Courses</h1>

<div class="row">
  {% for course in courses %}
  <div class="col-lg-4 col-md-4">
    <div class="card card-cascade">
      <div class="view view-cascade overlay">
        <img
          src="{{ course.thumbnail.url }}"
          class="card-img-top"
          alt="normal"
        />
      </div>
      <div class="card-body card-body-cascade text-center">
        <h4 class="card-title"><strong>{{ course.title }}</strong></h4>
        <p class="card-text">
          {{ course.description|truncatechars:150 }}
        </p>
      </div>
      <a href="" class="btn btn-primary">
        View Course
      </a>
    </div>
  </div>
  {% endfor %}
</div>

{% endblock %}

courses/templates/courses/course_detail.html
{% extends 'landing/base.html' %}

{% block content %}

<h1 style="text-align: center; padding: 20px;">{{course.title}}</h1>

<div class="row">
    
    <div class="col-lg-12 col-md-12">
      <div class="card card-cascade">
        <div class="view view-cascade overlay">
          <img
            src="{{ course.thumbnail.url }}"
            class="card-img-top"
          />
        </div>
        <div class="card-body card-body-cascade text-center">
          <h4 class="card-title"><strong>{{ lesson.course.title }}</strong></h4>
          <p class="card-text">
            {{ course.description|truncatechars:150 }}
          </p>
        </div>
        <div class="row">
            <div class="col">
            </div>
            <div class="col">
        <a href="" style="width: 8rem;" class="btn btn-primary">Buy Course</a>
    </div> <div class="col">
        <a href="" style="width: 8rem;" class="btn btn-danger">Wishlist</a>
    </div>
    <div class="col">
        <a href="" style="width: 8rem;" class="btn btn-success">Start</a>
    </div>
    <div class="col">
    </div>
</div>
    </div>
    </div>
  </div>
  


  {% endblock %}

landing/templates/landing/about.html
{% extends 'landing/base.html' %}

{% load static %}


{% block content %}
<!-- Grid row -->
<div class="row">

  
    <!-- Grid column -->
    <div class="col-lg-4 col-md-4">
  
        <!--Card Regular-->
        <div class="card card-cascade">
    
          <!--Card image-->
          <div style="border-radius: 50%;" class="view view-cascade overlay">
            <img src="{% static 'images/image1.PNG' %}" class="card-img-top" alt="normal">
            <a>
              <div class="mask rgba-white-slight"></div>
            </a>
          </div>
          <!--/.Card image-->
    
          <!--Card content-->
          <div class="card-body card-body-cascade text-center">
            <!--Title-->
            <h4 class="card-title"><strong>Abhimanyu Rathore</strong></h4>
            <h5>CEO & Founder - Solar Study</h5>
    
            <p class="card-text">Previously worked with Maharashtra (India), Rajasthan (India) state governments, TATA STRIVE, and World bank (Suprabha Scheme in India). Awarded TimesNext Super30 for Solar Study. 
            If you're looking for strategic collaboration with Solar Study, he's the person you need to connect. 
              unnamed.png
            </p>
    
            <!--Facebook-->
            <a type="button" class="btn-floating btn-small btn-fb"><i class="fab fa-facebook-f"></i></a>
            <!--Twitter-->
            <a type="button" class="btn-floating btn-small btn-tw"><i class="fab fa-twitter"></i></a>
            <!--Google +-->
            <a type="button" class="btn-floating btn-small btn-dribbble"><i class="fab fa-dribbble"></i></a>
    
          </div>
          <!--/.Card content-->
    
        </div>
        <!--/.Card Regular-->
    
      </div>
      <!-- Grid column -->
  
    <!-- Grid column -->
    <div class="col-lg-4 col-md-4">
  
      <!--Card Regular-->
      <div class="card card-cascade">
  
        <!--Card image-->
        <div class="view view-cascade overlay">
          <img src="{% static 'images/image2.PNG' %}" class="card-img-top" alt="normal">
          <a>
            <div class="mask rgba-white-slight"></div>
          </a>
        </div>
        <!--/.Card image-->
  
        <!--Card content-->
        <div class="card-body card-body-cascade text-center">
          <!--Title-->
          <h4 class="card-title"><strong>Subrahmanyam Pulipaka</strong></h4>
          <h5>Instructor - Solar Study | CEO -NSEFI | BITS P</h5>
  
          <p class="card-text">Subrahmanyam is the youngest Chief Executive Officer of National Solar Energy Federation of India. Subrahmanyam, who is BITSAA Global 30 Under 30 Award recipient, is an alumnus of BITS Pilani in Electrical & Electronics Engineering and is one of the youngest winners of BRICS young scientist award - 2018. Well known Speaker at various Solar and RE events in India,Pulipaka represented India in various scientific and technology platforms worldwide including United States, China, Russia and Rwanda. With a research background in reliability of solar PV modules, he has published around 15 research articles in internationally acclaimed journals. He is also the founding chairman of India Africa Youth Energy Forum, a platform dedicated to nurture future energy leaders in the Indian subcontinent and African continent. 
          </p>
  
          <!--Facebook-->
          <a type="button" class="btn-floating btn-small btn-fb"><i class="fab fa-facebook-f"></i></a>
          <!--Twitter-->
          <a type="button" class="btn-floating btn-small btn-tw"><i class="fab fa-twitter"></i></a>
          <!--Google +-->
          <a type="button" class="btn-floating btn-small btn-dribbble"><i class="fab fa-dribbble"></i></a>
  
        </div>
        <!--/.Card content-->
  
      </div>
      <!--/.Card Regular-->
  
    </div>
    <!-- Grid column -->

    <!-- Grid column -->
    <div class="col-lg-4 col-md-4">
  
        <!--Card Regular-->
        <div class="card card-cascade">
    
          <!--Card image-->
          <div class="view view-cascade overlay">
            <img src="{% static 'images/image3.PNG' %}" class="card-img-top" alt="normal">
            <a>
              <div class="mask rgba-white-slight"></div>
            </a>
          </div>
          <!--/.Card image-->
    
          <!--Card content-->
          <div class="card-body card-body-cascade text-center">
            <!--Title-->
            <h4 class="card-title"><strong>Dinesh Kumbharwar</strong></h4>
            <h5>Instructor - Solar Study | Certified NABCEP PV Associate | M.tech - IIT Bombay | IISc | VNIT </h5>
    
            <p class="card-text">Experienced Solar PV Engineer working as Assistant Manager (Engineering & Projects) at Solar firm. Executed around 1.5 MW of rooftop solar on-grid projects during the last 2 years of work tenure with Project Management. Strong technical professional with a Master of Technology focused in Energy System Engineering from the Indian Institute of Technology, Bombay, and Bachelor in technology in Electrical and Electronics from Visvesvaraya National Institute of Technology Nagpur. 
            </p>
    
            <!--Facebook-->
            <a type="button" class="btn-floating btn-small"></a>
            <!--Twitter-->
            <a type="button" class="btn-floating btn-small btn-tw"><i class="fab fa-twitter"></i></a>
            <!--Google +-->
            <a type="button" class="btn-floating btn-small btn-dribbble"><i class="fab fa-dribbble"></i></a>
    
          </div>
          <!--/.Card content-->
    
        </div>
        <!--/.Card Regular-->
    
      </div>
      <!-- Grid column -->


  </div>
  <!-- Grid row -->

  {% endblock %}

landing/templates/landing/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
</head>
<body>
    <!-- navbar start-->
        
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'landing:home' %}">Solar Study</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'landing:home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'landing:about' %}">About</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'courses:all_courses' %}">Courses</a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Welcome, {{request.user.username|upper}}
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'landing:profile' %}">Profile</a>
              <a class="dropdown-item" href="#">My Courses </a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'landing:logout' %}">Log Out</a>
            </div>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'landing:login' %}">Login </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'landing:signup' %}">Signup </a>
          </li>
          {% endif %}
    </div>
    
  </nav>

    <!-- navbar end -->


 {% block content%}





 {% endblock %}

 <!-- footer starts -->
<!-- Footer -->
<footer class="page-footer font-small stylish-color-dark pt-4">

    <!-- Footer Links -->
    <div class="container text-center text-md-left">
  
      <!-- Grid row -->
      <div class="row">
  
        <!-- Grid column -->
        <div class="col-md-4 mx-auto">
  
          <!-- Content -->
          <h5 class="font-weight-bold text-uppercase mt-3 mb-4">Solar Study</h5>
          <p>C/O Pushpendra Singh, Rajputo ka bas, Siwas, VPO Khinwara, Pali, Rajasthan - 306502 </p>
  
        </div>
        <!-- Grid column -->
  
        <hr class="clearfix w-100 d-md-none">
  
        <!-- Grid column -->
        <div class="col-md-2 mx-auto">
  
          <!-- Links -->
          <h5 class="font-weight-bold text-uppercase mt-3 mb-4">Quick Links </h5>
  
          <ul class="list-unstyled">
            <li>
              <a href="{% url 'landing:about' %}">About</a>
            </li>
            <br>
            <li>
              <a href="#!">Solar Study Fellowship </a>
            </li>
            <br>
            <li>
              <a href="{% url 'courses:all_courses' %}">Online Campus</a>
            </li>
          </ul>
  
        </div>
        <!-- Grid column -->
  
        <hr class="clearfix w-100 d-md-none">
  
        <!-- Grid column -->
        <div class="col-md-2 mx-auto">
  
          <!-- Links -->
          <h5 class="font-weight-bold text-uppercase mt-3 mb-4">Legal</h5>
  
          <ul class="list-unstyled">
            <li>
              <a href="{% url 'landing:terms' %}">Terms of use</a>
            </li>
            <br>
            <li>
              <a style="font-size: 15px;" href="{% url 'landing:terms' %}">Privacy Policy</a>
            </li>
          </ul>
  
        </div>
        <!-- Grid column -->
  
        <hr class="clearfix w-100 d-md-none">
  
      </div>
      <!-- Grid row -->
  
    </div>
    <!-- Footer Links -->
    <hr>
  
    <!-- Social buttons -->
    <ul class="list-unstyled list-inline text-center">
      <li class="list-inline-item">
        <a class="btn-floating btn-fb mx-1">
          <i class="fab fa-facebook-f"> </i>
        </a>
      </li>
      <li class="list-inline-item">
        <a class="btn-floating btn-tw mx-1">
          <i class="fab fa-twitter"> </i>
        </a>
      </li>
      <li class="list-inline-item">
        <a class="btn-floating btn-gplus mx-1">
          <i class="fab fa-google-plus-g"> </i>
        </a>
      </li>
      <li class="list-inline-item">
        <a class="btn-floating btn-li mx-1">
          <i class="fab fa-linkedin-in"> </i>
        </a>
      </li>
      <li class="list-inline-item">
        <a class="btn-floating btn-dribbble mx-1">
          <i class="fab fa-dribbble"> </i>
        </a>
      </li>
    </ul>
    <!-- Social buttons -->
  
    <!-- Copyright -->
    <div class="footer-copyright text-center py-3">© 2020 Copyright:
      <a href="{% url 'landing:home' %}"> Solar Study ™</a>
    </div>
    <!-- Copyright -->
  
  </footer>
  <!-- Footer -->
 <!-- footer ends  -->
    <!-- JS, Popper.js, and jQuery -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>

landing/templates/landing/body.html
{% extends 'landing/base.html' %}

{% load static %}


{% block content %}
<div class="row">
    <div class="col-sm-8">
        <h1>Solar Study   - Learning</h1>
        <br>
        <h5>Enhance your Solar Energy Knowledge </h5>
        <br>
        <input style="width: 400px;" class="form-control" type="text" placeholder="Search" aria-label="Search">
    </div>
    <div class="col-sm-4">
        <span></span>
    </div>
</div>
<hr>
<div class="row">
    <div class="col-5">

        <h3>Begin your career in Solar PV Industry with Gold standard online certification programme</h3>
        
    </div>
    <div style="text-align: center;" class="col-7">

        <h3> Solar Study Fellowship </h3>
        <br>
        <p>It is an online course in Solar Energy domain, which is among very few NABCEP (North American Board For Certified Energy Pracitioners) PVA, programme in ASIA.</p>
        <p>SSF is broadly divided into five domains: I. PV Applications, II. PV Sales & Economics, III. PV Design & Simulation, IV. PV Installation, and V. PV Operations & Maintenance</p>
        <br>
        <a class="btn btn-primary" href="">Explore More</a>    
    </div>
</div>
<hr>
<div class="row">

    <div class="col">
        <h2>Online Campus </h2>
            <br>
            <div class="view overlay zoom">
                <img src="https://mdbootstrap.com/img/Photos/Horizontal/Nature/6-col/img%20(131).jpg" class="img-fluid " alt="zoom">
                <div class="mask flex-center waves-effect waves-light">
                </div>
            </div>
            <br>
        <h5>Categories</h5>
                <br> <br>
        <div class="container">
            <div class="row">
                <div style="text-align: center;" class="card card-body">
              <div class="col">Buisness</div>
              <br>
              <div class="col">Marketing</div>
              
              <br><div class="col">Design</div>
              <br>
              <div class="col">Finance</div>
              <br>
              <div class="col">Installation</div>
              <br>
              <div class="col">Monitoring</div>
              
              <br>
              <div class="col">Applications</div>
              <br>
              <div class="col">Software</div>
              <br>
              <div style="text-align: center;">
                <a href="{% url 'courses:all_courses' %}" class="btn btn-info">Explore More</a>
              </div>
            </div>
            </div>
            
          </div>
            
    </div>
    <div style="text-align:center" class="col">
        <h2>Get Course Recommendations </h2>
        <br><br>
        <p>Link your success with the most relevant online courses while getting personalized course recommendations from the experts </p>
        <div class="view overlay zoom">
            <img src="{% static 'images/recommendation.PNG' %}" class="img-fluid " alt="zoom">
            <div class="mask flex-center waves-effect waves-light">
            </div>
        </div>
        <br>
        <button type="button" class="btn btn-warning">Get Recomendations</button>
    </div>
</div>

{% endblock %}

landing/templates/landing/login.html
{% extends 'landing/base.html' %}

{% block content %}

<div class="card card-body">
    <form action="" method="POST">
        {% csrf_token %}
        <input type="text" name="username" placeholder="Username..">
        <input type="password" name="password" placeholder="Password..">
        <input class="btn btn-success row" type="submit" value="Login">
    </form>
    {% for message in messages %}
    <p class="card-text">{{ message }}</p>
    {% endfor %}
</div>
<div class="row">
    <div class="col-3">
    <p>New here??  </p>
    <a class="btn btn-warning" href="{% url 'landing:signup' %}"> Signup </a>
</div>
<div class="col-3">
    <p>Can't login to your account? </p>    
    <a class="btn btn-warning" href="{% url 'landing:password_reset' %}"> Forget Password</a>

</div>
</div>

    {% endblock %}

landing/templates/landing/password_reset.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
</head>
<body>
    <!-- navbar start-->
        
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'landing:home' %}">Solar Study</a>
  </nav>

<h3>Password Reset</h3>
<p>
    Forgotten your password? Enter your email address below, and we’ll email instructions for setting a new one.
</p>

<form action="" method="POST">
    {% csrf_token %}
    
    {{ form }}
    <input class="btn btn-secondary" type="submit" value="Send Email">
</form>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
  </html>

landing/templates/landing/password_reset_done.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
</head>
<body>
    <!-- navbar start-->
        
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'landing:home' %}">Solar Study</a>
  </nav>
<div class="card">
    <div class="card-body">
<h3 class="card-title">Password reset complete</h3>
<p class="card-text">
    Your password has been set. You may go ahead and log in now.

    </p>
    <a href="{% url 'landing:login' %}" class="btn btn-success"> Login</a>
</div>
</div>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
  </html>

landing/templates/landing/password_reset_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
</head>
<body>
    <!-- navbar start-->
        
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'landing:home' %}">Solar Study</a>
  </nav>

<h3>Enter New Password</h3>
<p>Please enter your New Password twice to confirm</p>

<form action="" method="POST">
    {% csrf_token %}
    
    {{ form }}
    <input class="btn btn-secondary" type="submit" name="Update Password">
</form>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
  </html>

landing/templates/landing/signup.html
{% extends 'landing/base.html' %}

{% block content %}

<div class="card">
<h1 class="card-title">Welcome to Solar Study </h1>

<form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
<input class="btn btn-secondary" type="submit" value="Create Account">
</form>
<br>
</div>
<div class="text-center">
<p>Already have an account? </p>
<a class="btn btn-info" href="{% url 'landing:login' %}"> Login</a>
</div>
{% endblock %}